image: registry.cn-shanghai.aliyuncs.com/choerodon-tools/cibase:0.9.1

stages:
  - build

build:
  stage: build
  script:
    - npm install --registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - chmod -R 755 node_modules
#    - npm run dist
#    - mv src/main/resources/lib/dist docker
    - npm run compile
    - echo '//${NPM_REGISTRY}:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --registry https://nexus.choerodon.com.cn/repository/private-npm/
    - curl -X POST -F token=${FRONT_REPOSITORY_TOKEN} -F ref=${REF_NAME} https://code.choerodon.com.cn/api/v4/projects/2760/trigger/pipeline
  only:
    refs:
      - restructure-front      