---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: model-service
spec:
  template:
    metadata:
      labels:
        name: model-service
        com.hand.hap.cloud.devops/deploy-stage-type: Deploy
        com.hand.hap.cloud.devops/service-code: model-service
        com.hand.hap.cloud.devops/service-managementPort: "8091"
        com.hand.hap.cloud.devops/service-type: MicroService
    spec:
      containers:
      - name: model-service
        image: registry.saas.hand-china.com/choerodon-devops/devops-service:201848123123
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          protocol: TCP
        env:
        - name: EUREKA_DEFAULT_ZONE
          value: http://register-server.io-choerodon:8000/eureka/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://devops-mysql.db.svc:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: handhand
        - name: CHOERODON_EVENT_CONSUMER_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-0.kafka-headless.kafka.svc.cluster.local:9092, kafka-1.kafka-headless.kafka.svc.cluster.local:9092, kafka-2.kafka-headless.kafka.svc.cluster.local:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka-0.kafka-headless.kafka.svc.cluster.local:9092, kafka-1.kafka-headless.kafka.svc.cluster.local:9092, kafka-2.kafka-headless.kafka.svc.cluster.local:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.zookeeper.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.zookeeper.svc.cluster.local:2181
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.apache.kafka.common.serialization.ByteArraySerializer
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8010/
        readinessProbe:
          exec:
            command:
              - curl
              - 'localhost:8091/health'
          initialDelaySeconds: 60
          timeoutSeconds: 1
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
  replicas: 1
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: model-service
  name: model-service
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    name: model-service