spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devops_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
choerodon:
  event:
    consumer:
      enabled: true # 是否开启，不设置默认开启
      queue-type: kafka # 消息队列类型
      enable-duplicate-remove: false # 是否开启去重
      failed-strategy: nothing # 失败策略。支持nothing(什么都不做), send_back_event_store(回传到event store)两种
      retry:
        enabled: true # 是否开启重试功能
      kafka:
        bootstrap-servers: localhost:9092 # kafka地址
  swagger:
    oauthUrl: http://localhost:8080/oauth/oauth/authorize
    skip:
        service: register-server, api-gateway, gateway-helper, oauth-server, config-server
  gateway:
    domain: localhost:8080
    names: api-gateway, gateway-helper