spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 842767365
  cloud:
      bus:
        enabled: true
      stream:
        kafka:
          binder:
            brokers: 10.211.111.130:9092
            zkNodes: 10.211.111.130:2181
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://10.211.111.130:8000/eureka/}
    registryFetchIntervalSeconds: 10

logging:
  level:
    root: info
    io.choerodon.workflow: debug