# Default values for manager-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

preJob:
  preConfig:
    mysql:
      host: 192.168.12.113
      port: 3309
      database: helm_test
      username: root
      password: handhand
    configFile: application-default.yml    
  preInitDB:
    mysql:
      host: 192.168.12.113
      port: 3309
      database: helm_test
      username: root
      password: handhand

deployment:
  managementPort: 8964

image:
  repository: registry.saas.hand-china.com/choerodon-framework/manager-service
  tag: develop.20180327155006
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8963

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
  #  cpu: 100m
   memory: 3Gi
  requests:
  #  cpu: 100m
   memory: 2Gi