# Default values for manager-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.saas.hand-china.com/choerodon-devops/devops-service
  tag: develop.20180502154450
  pullPolicy: Always

preJob:
  preConfig:
    configFile: application-default.yml
    mysql:
      host: 192.168.12.175
      port: 3306
      database: manager_service
      username: root
      password: handhand
  preInitDB:
    mysql:
      host: 192.168.12.175
      port: 3306
      database: devops_service
      username: root
      password: handhand

deployment:
  managementPort: 8061

env:
  open:
    SPRING_REDIS_HOST: devops-redis.devops.svc
    EUREKA_DEFAULT_ZONE: http://register-server.io-choerodon:8000/eureka/
    SPRING_DATASOURCE_URL: jdbc:mysql://hapcloud-mysql.db.svc:3306/devops_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: handhand
    CHOERODON_EVENT_CONSUMER_KAFKA_BOOTSTRAP_SERVERS: kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092
    SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092
    SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.zookeeper.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.zookeeper.svc.cluster.local:2181
    SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.ByteArraySerializer
    SPRING_CLOUD_CONFIG_URI: http://config-server.framework:8010/
    GITLAB_URL: http://gitlab.alpha.saas.hand-china.com

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:

service:
  enabled: false
  type: ClusterIP
  port: 8060

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 4Gi
  requests:
    # cpu: 100m
    memory: 2Gi