apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "{{service.code}}.fullname" . }}-init-config
  labels:
{{ include "{{service.code}}.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-init-config
      labels:
{{ include "{{service.code}}.labels.standard" . | indent 8 }}
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - cp -rf /var/choerodon/* /tools
        image: registry.saas.hand-china.com/tools/choerodon-tools:0.1.0
        imagePullPolicy: Always
        name: tools
        volumeMounts:
        - mountPath: /tools
          name: tools-jar
      containers:
      - name: {{ .Chart.Name }}-init-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - /bin/sh
        - -c
        - '
          java -Dspring.datasource.url="jdbc:mysql://{{ .Values.preJob.preConfig.mysql.host }}:{{ .Values.preJob.preConfig.mysql.port }}/{{ .Values.preJob.preConfig.mysql.database }}?useUnicode=true&characterEncoding=utf-8&useSSL=false" -Dspring.datasource.username={{ .Values.preJob.preConfig.mysql.username }} -Dspring.datasource.password={{ .Values.preJob.preConfig.mysql.password }} -Dservice.name={{ .Chart.Name }} -Dservice.version={{ .Values.image.tag }} -Dconfig.file={{ .Values.preJob.preConfig.configFile }} -Dconfig.jar=/app.jar -jar /var/choerodon/choerodon-tool-config.jar;
          '
        volumeMounts:
        - mountPath: /var/choerodon
          name: tools-jar
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: tools-jar