apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ include "{{service.code}}.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "{{service.code}}.labels.standard" . | indent 4 }}